apps/services/urls.py
# coding=utf-8
from django.conf.urls import url
from apps.services.views import PriceView, ViewQRCode

urlpatterns =[
    url(r'^price/$', PriceView.as_view(), name='price'),
    url(r'^qrCode/', ViewQRCode.as_view(), name='qr_code'),
]

ryabina/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from filebrowser.sites import site as fb_site
from ryabina.sitemaps import StaticViewSitemap


sitemaps = {
    'static': StaticViewSitemap
}

urlpatterns = [
    url(r'^admin/filebrowser/', include(fb_site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('apps.pages.urls', namespace='pages')),
    url(r'^services/', include('apps.services.urls', namespace='services')),
    url(r'^questions/', include('apps.questions.urls', namespace='questions')),
    url(r'^comments/', include('apps.custom_comments.urls', namespace='custom_comments')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

apps/discounts/models.py
# coding=utf-8

from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
from apps.services.models import Service


class Discount(models.Model):
    title = models.CharField(u'заголовок', max_length=255)
    image = models.ImageField(upload_to='img/discount', verbose_name=u'рисунок')
    content = HTMLField(u'содержимое', blank=True, null=True)
    url = models.CharField(u'ссылка на страницу', max_length=255, blank=True, null=True)
    button = models.CharField(u'надпись на кнопке', max_length=255, blank=True, null=True)
    current_price = models.IntegerField(u'текущая цена', blank=True, null=True)
    old_price = models.IntegerField(u'старая цена', blank=True, null=True)
    percent = models.IntegerField(u'скидка в процентах', blank=True, null=True, help_text=u'если указаны проценты, то в объявлении показываются проценты')
    created_at = models.DateTimeField(u'дата начала', default=timezone.now)
    close_at = models.DateTimeField(u'дата закрытия', blank=True, null=True, help_text=u'дата автоматического снятия с показа')
    is_published = models.BooleanField(u'опубликовано', default=True)
    services = models.ManyToManyField(Service, verbose_name=u'связанные услуги', blank=True)

    class Meta:
        ordering = ('-created_at',)
        verbose_name = u'акция'
        verbose_name_plural = u'акции'

    def __unicode__(self):
        return self.title

    def get_discount(self):
        if self.percent:
            return u'-%%%s' % self.percent
        else:
            if self.current_price:
                return u'%s' % self.current_price
            else:
                return u'бесплатно'

apps/services/models.py
# coding=utf-8

from django.db import models
from treebeard.mp_tree import MP_Node


class ServiceIcon(models.Model):
    image = models.FileField(u'рисунок', upload_to='img/courses')
    title = models.CharField(u'заголовок', max_length=255, blank=True, null=True)

    class Meta:
        verbose_name = u'иконка'
        verbose_name_plural = u'иконки услуг'

    def __unicode__(self):
        return self.title


class ServiceCourse(models.Model):
    title = models.CharField(u'заголовок', max_length=255, blank=True, null=True)
    short_title = models.CharField(u'короткий заголовок', max_length=255, blank=True, null=True)
    icon = models.ForeignKey(ServiceIcon, verbose_name='иконка', blank=True, null=True)
    on_main_page = models.BooleanField(u'на главной странице', default=False)
    description = models.TextField(u'описание', blank=True, null=True)
    url = models.CharField(u'ссылка на страницу', max_length=255, blank=True, null=True)
    button = models.CharField(u'надпись на кнопке', max_length=255, blank=True, null=True)

    class Meta:
        ordering = ('title',)
        verbose_name = u'направление'
        verbose_name_plural = u'направления услуг'

    def __unicode__(self):
        return self.get_short_title()

    def get_short_title(self):
        return u'%s' % self.short_title if self.short_title else self.title

    # def get_services(self):
    #     return Service.objects.filter(course=self)


class ServiceCategory(models.Model):
    title = models.CharField(u'заголовок', max_length=255)
    description = models.TextField(u'описание', blank=True, null=True)

    class Meta:
        ordering = ('title',)
        verbose_name = u'категория'
        verbose_name_plural = u'категории услуг'

    def __unicode__(self):
        return self.title

    def get_services_count(self):
        return self.service_set.all().count()
    get_services_count.short_description = u'Услуг'


class Service(MP_Node):
    title = models.CharField(u'заголовок', max_length=255)
    min_price = models.IntegerField(u'минимальная цена', blank=True, null=True)
    max_price = models.IntegerField(u'максимальная цена', blank=True, null=True)
    course = models.ForeignKey(ServiceCourse, verbose_name='направление', blank=True, null=True)
    category = models.ManyToManyField(ServiceCategory, verbose_name='категория', blank=True)

    node_order_by = ['course', 'title']

    class Meta:
        verbose_name = u'услуга'
        verbose_name_plural = u'услуги'

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.min_price > self.max_price:
            self.min_price, self.max_price = self.max_price, self.min_price
        super(Service, self).save(*args, **kwargs)

    def get_price(self):
        if self.min_price and self.max_price:
            if self.min_price==self.max_price:
                return u'%d' % self.min_price
            else:
                return u'от %d до %d' % (self.min_price, self.max_price)
        elif self.min_price and not self.max_price:
            return u'от %d' % self.min_price
        elif self.max_price and not self.min_price:
            return u'до %d' % self.max_price
        else:
            return None

    def get_categories(self):
        return self.category.all()

    def get_categories_changelist(self):
        return u'<br>'.join(self.get_categories().values_list('title', flat=True))
    get_categories_changelist.short_description = u'Категории'
    get_categories_changelist.allow_tags = True

    def get_price_changelist(self):
        return self.get_price()
    get_price_changelist.short_description = u'Стоимость'

apps/services/views.py
# coding=utf-8
from StringIO import StringIO
import PIL
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseServerError, HttpResponseBadRequest
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.template.loader import get_template
from django.views.generic import View
import qrcode
from xhtml2pdf import pisa
from django.utils import timezone
from apps.discounts.models import Discount
from apps.services.models import Service, ServiceCourse


class PriceView(View):
    template_name = 'price_pdf.html'
    def get(self, request):
        now = timezone.now()
        context = {
            'courses': ServiceCourse.objects.all(),
            'services': Service.get_annotated_list(),
            'discounts': Discount.objects.filter(is_published=True, created_at__lt=now).exclude(close_at__lte=now),
            'qr_data': 'http://%s%s' % (get_current_site(request), reverse('pages:services')),
            'qr_host': 'www.ryabinaclinic.ru'
        }

        template = get_template(self.template_name)
        # return render_to_response(self.template_name, context, context_instance=RequestContext(request))

        result = StringIO()
        pdf = pisa.pisaDocument(StringIO(template.render(context).encode("UTF-8")), result)
        if not pdf.err:
            response = HttpResponse(result.getvalue(), content_type='application/pdf')
            response['Content-Disposition'] = 'attachment; filename=ryabina_price_%s.pdf' % timezone.now().strftime('_%Y_%m_%d__%H_%M')
            return response
        else:
            return HttpResponseServerError()


class ViewQRCode(View):
    def get(self, request):
        if 'qr_pass_phrase' in request.GET and len(request.GET['qr_pass_phrase']) and request.GET['qr_pass_phrase'] == settings.QR_PASS_PHRASE:
            if 'data' in request.GET and len(request.GET['data']):
                info = request.GET['info']
            else:
                info = u'(Ryabina, %s) http://www.ryabina-stom.ru' % timezone.now().strftime('%Y')

            qr = qrcode.QRCode(
                version=1,
                error_correction=qrcode.constants.ERROR_CORRECT_L,
                box_size=10,
                border=0,
            )
            qr.add_data(info)
            qr.make(fit=True)

            img = qr.make_image()

            try:
                size = int(request.GET['size']) if 'size' in request.GET and len(request.GET['size']) else 300
            except ValueError:
                size = 300

            img_ratio = size/float(img._img.size[0])
            img = img._img.resize([int(img_ratio * s) for s in img._img.size], PIL.Image.ANTIALIAS)

            response = HttpResponse(content_type='image/png')
            img.save(response,'png')

            return response
        else:
            return HttpResponseBadRequest()

apps/services/templates/price_pdf.html
{% load kwacros portal_templatetags services_templatetags %}
{% kwacro services_info service_annotated_list=None %}
        {% for service_item, info in service_annotated_list %}
            {% if info.open %}
                {% if not forloop.first %}<ul>{% endif %}
                <li>
            {% else %}
                </li><li>
            {% endif %}

            {% with service_item.get_children as service_children %}
                {% if service_children|length %}
                    <table cellpadding="5" cellspacing="0" border="0">
                    <tr>
                        <td valign="top" align="left"><span class="title">{{ service_item.title }}</span></td>
                    </tr>
                    </table>
                {% else %}
                    {% with service_item.get_price as item_price %}
                    {% with service_item.discount_set.all as discount_set %}
                    <table cellpadding="5" cellspacing="0" border="0">
                    <tr>
                        <td valign="top" align="left"><span class="item">{{ service_item.title }}</span></td>
                        <td width="268px" valign="top" align="right"><span class="price">{% if item_price %}{{ item_price }} р.{% else %}{% endif %}</span></td>
                    </tr>
                    </table>
                    {% if discount_set|length %}
                        <table cellpadding="5" cellspacing="0" border="0">
                        {% for discount in discount_set %}
                        <tr>
                            <td valign="top" align="left"><span class="discount">Акция! </span><span class="item">"{{ discount.title }}" с {{  discount.created_at|date:"SHORT_DATE_FORMAT" }}{% if discount.close_at %} до {{  discount.close_at|date:"SHORT_DATE_FORMAT" }}{% endif %}</span></td>
                            <td width="268px" valign="top" align="right"><span class="price">
                            {% if discount.percent %}
                                -{{ discount.percent }}%
                            {% else %}
                                {% if discount.current_price %}
                                    {{ discount.current_price }} р.
                                {% else %}
                                    БЕСПЛАТНО
                                {% endif %}
                            {% endif %}
                            </span></td>
                        </tr>
                        {% endfor %}
                        </table>
                    {% endif %}
                    {% endwith %}
                    {% endwith %}
                {% endif %}
            {% endwith %}

            {% with forloop.last as parent_last %}
            {% for close in info.close %}
                </li>
                {% if parent_last and forloop.last %}{% else %}</ul>{% endif %}
            {% endfor %}
            {% endwith %}
        {% endfor %}
{% endkwacro %}
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Прейскурант на услуги стоматологического центра "Рябина"</title>

    <style type="text/css">
        @page {
            size: A4;
            margin: 0.7cm 0.7cm 1.4cm 0.7cm;

            @frame header_frame {
                -pdf-frame-content: header_content;
                left: 0.7cm;
                top: 0.7cm;
                height: 0.1cm;
                width: 19.6cm;
            }

            @frame footer_frame {
                -pdf-frame-content: footer_content;
                left:0.7cm;
                height: 0.7cm;
                width: 19.6cm;
                bottom: 0.7cm;
            }
        }

        @font-face {
            font-family: OpenSans;
            src: url('{% static_dir %}font/OpenSans/OpenSans-Regular.ttf');
        }

        @font-face {
            font-family: OpenSansBold;
            src: url('{% static_dir %}font/OpenSans/OpenSans-Bold.ttf');
        }

        @font-face {
            font-family: OpenSansItalic;
            src: url('{% static_dir %}font/OpenSans/OpenSans-Italic.ttf');
        }

        @font-face {
            font-family: OpenSansBoldItalic;
            src: url('{% static_dir %}font/OpenSans/OpenSans-BoldItalic.ttf');
        }

        #footer_content{
            font-family: "OpenSans", Tahoma, sans-serif;
            text-align: left;
            }

        #header_content{
            text-align: right;
            font-family: "OpenSans", Tahoma, sans-serif;
        }

        body {
           font-family: OpenSans;
           font-size: 9pt;
        }

        span.h1{
            font-family: OpenSansBold;
            font-size: 19pt;
        }

        span.h2{
            font-family: OpenSansBold;
            font-size: 12pt;
        }

        span.footer{
            font-family: OpenSansItalic;
            font-size: 24pt;
        }

        span.header{
            font-family: OpenSansBold;
            font-size: 12pt;
        }

        span.title{
            font-size: 10pt;
            font-family: OpenSansBold;
        }

        span.item{
            font-size: 10pt;
            font-family: OpenSans;
        }

        span.discount{
            font-size: 10pt;
            font-family: OpenSansItalic;
            color: red;
        }

        span.discount_title{
            font-size: 12pt;
            font-family: OpenSans;
        }

        span.discount_price{
            font-size: 14pt;
            font-family: OpenSans;
            color: red;
        }

        span.price{
            font-size: 10pt;
            font-family: OpenSans;
        }

        table{
            padding: 0px;
        }

        li{
            list-style: none;
        }

    </style>
</head>
<body>
<div id="header_content"></div>
<div id="footer_content">
Прейскурант на услуги стоматологического центра "Рябина" от {% now "SHORT_DATE_FORMAT" %} / стр. <pdf:pagenumber> из
<pdf:pagecount>
</div>
<div id="main_content">
    <table cellpadding="0" cellspacing="0" border="0" height="106px">
        <tr>
            <td width="226px"><img src="{% static_dir %}img/logo/report.jpg" height="106px"></td>
            <td width="508px" valign="top">
                <table cellpadding="5" cellspacing="0" border="0">
                    <tr>
                        <td align="left"><span class="h1">Стоматологический центр "Рябина"</span></td>
                    </tr>
                    <tr>
                        <td align="left"><span class="h2">Прейскурант на стоматологические услуги от {% now "SHORT_DATE_FORMAT" %}</span></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <table cellpadding="0" cellspacing="0" border="0" style="width:768px; height:10px;"><tr><td>&nbsp;</td></tr></table>
    {% for course in courses %}
        <ul>
        {% get_course_services course as services %}
        {% if services|length %}
        <li>
        <table cellpadding="0" cellspacing="0" border="0" style="width:768px; height:10px;"><tr><td>&nbsp;</td></tr></table>
        <table cellpadding="0" cellspacing="0" border="0" style="width:768px;">
        <tr>
            <td width="768px" valign="top" align="center" colspan="3"><span class="header">{{ course.title }}</span></td>
        </tr>
        </table>
        <table cellpadding="0" cellspacing="0" border="0" style="width:768px; height:10px;"><tr><td>&nbsp;</td></tr></table>
        </li>
        {% for course_service in services %}
            {% get_services_annotated_list course_service as services_annotated_list %}
            {% usekwacro services_info service_annotated_list=services_annotated_list %}
        {% endfor %}
        {% endif %}
        </ul>
    {% endfor %}
    {% if discounts|length %}
    <table cellpadding="0" cellspacing="0" border="0" style="width:768px; height:10px;"><tr><td>&nbsp;</td></tr></table>
    <table cellpadding="0" cellspacing="0" border="0" style="width:768px;">
        <tr>
            <td width="768px" valign="top" align="center" colspan="3"><span class="header">Акции и скидки</span></td>
        </tr>
    {% for discount in discounts %}
        {% cycle 1 2 as row silent %}
        {% if row == 1 %}<tr><td>&nbsp;</td></tr><tr>{% endif %}
        {% if row == 2 %}<td width="10px">&nbsp;</td>{% endif %}
            <td width="379px" align="center" valign="top">
                <table cellpadding="0" cellspacing="5" border="0" style="width:384px;">
                    <tr>
                        <td><span class="discount_title">{{ discount.title }}</span></td>
                    </tr>
                    <tr><td>&nbsp;</td></tr>
                    {% if discount.image %}
                    <tr>
                        <td><img src="{% media_dir %}{{ discount.image }}" width="380px"></td>
                    </tr>
                    <tr><td>&nbsp;</td></tr>
                    {% endif %}
                    <tr>
                        <td><span class="discount_price">{% if discount.percent %}Скидка {{ discount.percent }}%{% else %}{% if discount.price or discount.old_price %}{% if discount.old_price %}<strike>{{ discount.old_price }}</strike> {% endif %}{{ discount.current_price }} р.{% else %}БЕСПЛАТНО{% endif %}{% endif %}</span></td>
                    </tr>
                    <tr><td>&nbsp;</td></tr>
                    <tr>
                        <td align="left">{{ discount.content|striptags|safe }}</td>
                    </tr>
                    <tr>
                        <td align="right">Акция действует с {{ discount.created_at|date:"SHORT_DATE_FORMAT" }}{% if discount.close_at %} до {{ discount.close_at|date:"SHORT_DATE_FORMAT" }}{% endif %}</td>
                    </tr>
                </table>
            </td>
        {% if row == 2 or forloop.last %}</tr>{% endif %}
    {% endfor %}
    </table>
    {% endif %}
    <table cellpadding="0" cellspacing="0" border="0" style="width:768px; height:10px;"><tr><td>&nbsp;</td></tr></table>
    <table cellpadding="0" cellspacing="10" border="0" style="width:768px;">
        <tr>
            <td width="768px" align="center">
                <span class="footer">Добро пожаловать в стоматологический центр "Рябина"!</span>
            </td>
        </tr>
    </table>
    <table cellpadding="0" cellspacing="0" border="0" style="width:768px; height:10px;"><tr><td>&nbsp;</td></tr></table>
    <table cellpadding="0" cellspacing="10" border="0" style="width:768px;">
        <tr>
            <td width="768px" height="150px" align="right">
               {% qr_code qr_host 150 qr_data %}
            </td>
        </tr>
    </table>
</div>
</body>
</html>